### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by yash101** [swhacks/swhacks.github.io#1]
Detailed FAQ for the site

**Comment by yash101** [comment]
https://docs.google.com/document/d/1QCp566rRzOoWxdOAw0GiFDhcOQX9DkZPkZwY_69vJJ8/edit?usp=sharing

**Comment by parion** [comment]
Thanks for the document. Will need more info.

**Comment by yash101** [comment]
FAQ created. Reopen or new issue when updates necessary
