### ISSUE TITLE
Links to stuff

### ISSUE THREAD

**Issue by yash101** [swhacks/swhacks.github.io#11]
Need permalinks to stuff:
- Facebook
- Twitter
- Email Address(es)
- Register
- Other important links that may be necessary

**Comment by stevex86-old** [comment]
Twitter link: https://twitter.com/SWHacks_2017

**Comment by stevex86-old** [comment]
Facebook link: https://www.facebook.com/swhacksofficial

**Comment by stevex86-old** [comment]
Current authoritative email link: team@swhacks.io

**Comment by yash101** [comment]
Cool! It's up!
