### ISSUE TITLE
Speakers Section

### ISSUE THREAD

**Issue by stevex86-old** [swhacks/swhacks.github.io#13]
Section would highlight our guest speakers at the event and explain why the audience should be excited to listen.

As sponsorships fall in, we may have a growing number of guest speakers.

Currently, Dean Squires is scheduled to speak at the event.

**Comment by yash101** [comment]
Holding off until Dean Squires gives us more information.

**Comment by yash101** [comment]
Shouldn't have closed. Will forget :/
