### ISSUE TITLE
Remove Clickability of FAQs

### ISSUE THREAD

**Issue by stevex86-old** [swhacks/swhacks.github.io#24]

**Comment by yash101** [comment]
I think it's perfectly fine. I added that to help with shareability. There's a bug so the browser doesn't scroll to the link after load. Will be fixed later as that affects other things too.

**Comment by stevex86-old** [comment]
Reopening just so it doesn't fall through the cracks later on if it will be fixed later.

**Comment by yash101** [comment]
Yeah I just made the "blocked" label :)

**Comment by yash101** [comment]
Fixed
